import { test, before } from "node:test";
import assert from "node:assert/strict";
import { prepararBase, G, ultimoEnviado } from "./helpers.mjs";

let F, C, Reg, HG, Pf, Hook, Cmd, Cal;
const DIA = 24 * 3600e3;
before(async () => {
  ({ F } = await prepararBase("compraventa"));
  C = await import("../lib/compraventa.js");
  Reg = await import("../lib/reglas.js");
  HG = await import("../lib/horario-grupo.js");
  Pf = await import("../lib/perfil.js");
  Hook = (await import("../plugins/_compraventa.js")).default;
  Cmd = (await import("../plugins/compraventa.js")).default;
  Cal = (await import("../plugins/calificar.js")).default;
  for (const n of [111, 222, 333]) F.initDataDB({ chat: G, sender: `${n}@lid`, senderJid: `${n}@s.whatsapp.net` });
});
let k = 0;
const msg = (sender, text) => ({ chat: G, sender, text, isGroup: true, key: { id: `K${++k}` } });
const cliente = () => globalThis.client;
const ultimo = () => ultimoEnviado().msg.text;
const correr = (sender, command, text = "", extra = {}) => Cmd.run(msg(sender, text), { client: cliente(), command, args: text.trim() ? text.trim().split(/\s+/) : [], text, isMod: false, ...extra });

test("compraventa: detección de hashtag y precio", () => {
  assert.deepEqual(C.detectarPublicacion("#vendo bici rodado 26 $ 4.000 Pocitos"), { tipo: "vendo", texto: "bici rodado 26 $ 4.000 Pocitos" });
  assert.deepEqual(C.detectarPublicacion("Hola! #busco heladera chica"), { tipo: "compro", texto: "Hola! heladera chica" });
  assert.equal(C.detectarPublicacion("vendo sin numeral"), null);
  assert.equal(C.detectarPublicacion("#vendox"), null);
  assert.equal(C.detectarPrecio("bici $ 4.000 Pocitos"), "$ 4.000");
  assert.equal(C.detectarPrecio("celular USD 200 usado"), "USD 200");
  assert.equal(C.detectarPrecio("mesa 1500 pesos"), "1500 pesos");
  assert.equal(C.detectarPrecio("tele u$s 350"), "u$s 350");
  assert.equal(C.detectarPrecio("regalo perro"), "");
});

test("compraventa: publicar por hashtag, catálogo, búsqueda, detalle y alertas", async () => {
  await correr("333@lid", "avisame", "heladera");
  assert.match(ultimo(), /te menciono cuando alguien publique algo con "heladera"/);
  await Hook.before(msg("111@lid", "#vendo bici rodado 26 $ 4.000 Pocitos"), { client: cliente() });
  assert.match(ultimo(), /🏷️ \*Vendo #1\* registrada\. Precio: \$ 4\.000\./);
  const p1 = F.getPublicacion(G, 1);
  assert.deepEqual([p1.tipo, p1.texto, p1.precio, p1.estado, p1.usuario], ["vendo", "bici rodado 26 $ 4.000 Pocitos", "$ 4.000", "activa", "111@lid"]);
  await Hook.before(msg("222@lid", "#compro heladera chica que ande"), { client: cliente() });
  const enviados = globalThis.enviados;
  assert.match(enviados[enviados.length - 2].msg.text, /🔎 \*Compro #2\* registrada\./);
  assert.match(ultimo(), /🔔 @333: apareció algo que buscabas\. Compro #2: heladera chica que ande/);
  assert.deepEqual(ultimoEnviado().msg.mentions, ["333@lid"]);
  await Hook.before(msg("111@lid", "#vendo mesa de luz"), { client: cliente() });
  assert.match(ultimo(), /Vendo #3\* registrada\. Se ve con \.vendo[\s\S]*no le pusiste precio/);
  await Hook.before(msg("111@lid", "che, alguien sabe algo?"), { client: cliente() });
  assert.match(ultimo(), /no le pusiste precio/, "sin hashtag no pasa nada");
  await correr("111@lid", "vendo");
  assert.match(ultimo(), /🏷️ \*EN VENTA\* \(2\)\n\*#3\* mesa de luz — @111\n\*#1\* bici rodado 26 \$ 4\.000 Pocitos — @111/);
  await correr("111@lid", "compro");
  assert.match(ultimo(), /🔎 \*SE BUSCA\* \(1\)\n\*#2\* heladera chica que ande — @222/);
  await correr("111@lid", "publicaciones");
  assert.match(ultimo(), /EN VENTA[\s\S]*SE BUSCA/);
  await correr("111@lid", "buscar", "Bici");
  assert.match(ultimo(), /Resultados para "Bici"\* \(1\)\n🏷️ \*#1\* bici/);
  await correr("111@lid", "buscar", "lavarropas");
  assert.match(ultimo(), /Nada activo con "lavarropas"\. Con \.avisame lavarropas/);
  await correr("111@lid", "publicacion", "1");
  assert.match(ultimo(), /🏷️ \*Vendo #1\* · activa\nbici rodado 26 \$ 4\.000 Pocitos\nPrecio: \$ 4\.000 · Publicó @111 hace/);
  await correr("111@lid", "publicacion", "99");
  assert.match(ultimo(), /No hay ninguna publicación #99/);
  await correr("222@lid", "vendo", "silla de oficina $ 2.500");
  assert.match(ultimo(), /Vendo #4\* registrada\. Precio: \$ 2\.500/);
  await correr("222@lid", "mias");
  assert.match(ultimo(), /Tus publicaciones activas\* \(2\)/);
  await correr("333@lid", "avisame");
  assert.match(ultimo(), /Tus alertas: heladera\./);
  await correr("333@lid", "avisame", "quitar heladera");
  assert.match(ultimo(), /saqué la alerta "heladera"/);
  await correr("333@lid", "avisame", "ab");
  assert.match(ultimo(), /al menos 3 letras/);
  for (const w of ["uno", "dos", "tres", "cuatro", "cinco"]) await correr("333@lid", "avisame", w);
  await correr("333@lid", "avisame", "seis");
  assert.match(ultimo(), /Ya tenés 5 alertas/);
});

test("compraventa: estados, permisos y vencimiento", async () => {
  await correr("222@lid", "vendido", "1");
  assert.match(ultimo(), /La #1 no es tuya/);
  await correr("222@lid", "vendido", "1", { isMod: true });
  assert.match(ultimo(), /la #1 quedó como concretada/);
  assert.equal(F.getPublicacion(G, 1).estado, "vendida");
  await correr("111@lid", "reservado", "1");
  assert.match(ultimo(), /ya está ✅ concretada\. Con \.sigue 1 la volvés a activar/);
  await correr("111@lid", "sigue", "1");
  assert.equal(F.getPublicacion(G, 1).estado, "activa");
  await correr("111@lid", "reservado", "1");
  assert.equal(F.getPublicacion(G, 1).estado, "reservada");
  await correr("111@lid", "vendo");
  assert.match(ultimo(), /🔒 \*#1\*/);
  await correr("111@lid", "baja", "3");
  assert.equal(F.getPublicacion(G, 3).estado, "cerrada");
  await correr("111@lid", "baja", "x");
  assert.match(ultimo(), /¿Cuál\? Poné el número/);
  const ahora = Date.now();
  F.actualizarPublicacion(G, 4, { actualizada: ahora - 8 * DIA });
  assert.equal(await C.chequearPublicaciones(ahora), 1);
  assert.match(ultimo(), /❓ @222, ¿sigue en pie tu vendo #4 \(silla de oficina \$ 2\.500\)\?/);
  assert.ok(F.getPublicacion(G, 4).aviso > 0);
  assert.equal(await C.chequearPublicaciones(ahora + DIA), 0, "todavía no venció el plazo para contestar");
  assert.equal(await C.chequearPublicaciones(ahora + 3 * DIA), 1);
  assert.equal(F.getPublicacion(G, 4).estado, "vencida");
  assert.match(ultimo(), /⌛ Di de baja la #4 de @222 por falta de respuesta/);
  await correr("222@lid", "sigue", "4");
  assert.deepEqual([F.getPublicacion(G, 4).estado, F.getPublicacion(G, 4).aviso], ["activa", 0]);
  for (let i = 0; i < 10; i++) await correr("333@lid", "vendo", `cosa ${i} $ 100`);
  await correr("333@lid", "vendo", "una más $ 100");
  assert.match(ultimo(), /Ya tenés 10 publicaciones activas/);
});

test("compraventa: calificaciones y reputación", async () => {
  const cal = (sender, text) => Cal.run(msg(sender, text), { client: cliente(), command: "calificar", args: text.split(/\s+/), text });
  await cal("222@lid", "@111 5 buen vendedor, rápido");
  assert.match(ultimo(), /⭐⭐⭐⭐⭐ Calificaste a @111: "buen vendedor, rápido"\. Ahora tiene 5,0 de 5 \(1 calificación\)\./);
  await cal("333@lid", "@111 4");
  assert.match(ultimo(), /Ahora tiene 4,5 de 5 \(2 calificaciones\)/);
  await cal("333@lid", "@111 2 me arrepentí");
  assert.match(ultimo(), /Actualicé tu calificación de este mes para @111/);
  assert.deepEqual(F.reputacionDe("111@lid"), { promedio: 3.5, cantidad: 2 });
  await cal("111@lid", "@111 5");
  assert.match(ultimo(), /A vos mismo no/);
  await cal("111@lid", "@222 9");
  assert.match(ultimo(), /van de 1 a 5/);
  await cal("111@lid", "5 sin mencion");
  assert.match(ultimo(), /¿A quién\?/);
  await cal("111@lid", "@999 5");
  assert.match(ultimo(), /No conozco a esa persona/);
  await Cal.run(msg("222@lid", "@111"), { client: cliente(), command: "reputacion", args: ["@111"], text: "@111" });
  assert.match(ultimo(), /⭐ Reputación de @111: \*3,5 de 5 \(2 calificaciones\)\*\n⭐⭐ "me arrepentí" — @333\n⭐⭐⭐⭐⭐ "buen vendedor, rápido" — @222/);
  await Cal.run(msg("333@lid", ""), { client: cliente(), command: "reputacion", args: [], text: "" });
  assert.match(ultimo(), /Tu reputación: todavía sin calificaciones/);
  assert.match(Pf.textoPerfil(G, "111@lid", F.getUser("111@lid")).texto, /⭐ Reputación: 3,5 de 5 \(2 calificaciones\)\n🏷️ 1 publicación activa/);
});

test("compraventa: reglas y plantilla", async () => {
  const Reglas = (await import("../plugins/grupo-reglas.js")).default;
  const run = (sender, command, text, isAdmin) => Reglas.run(msg(sender, text), { client: cliente(), command, args: text.trim() ? text.trim().split(/\s+/) : [], text, isAdmin });
  globalThis.txt = { onlyAdmin: "solo admins" };
  await run("111@lid", "reglas", "", false);
  assert.match(ultimo(), /no tiene reglas cargadas/);
  await run("111@lid", "reglas", "set no se aceptan reventas", false);
  assert.equal(ultimo(), "solo admins");
  await run("111@lid", "reglas", "set 1. Publicá con precio y zona\n2. Nada de reventas", true);
  assert.match(ultimo(), /reglas cargadas/);
  await run("222@lid", "reglas", "", false);
  assert.match(ultimo(), /📋 \*Reglas del grupo\*\n\n1\. Publicá con precio y zona\n2\. Nada de reventas/);
  const aviso = Reg.avisoReglasParaNuevos(G, ["444@lid", { id: "555@s.whatsapp.net" }]);
  assert.match(aviso.texto, /Bienvenid@s @444 @555[\s\S]*1\. Publicá con precio y zona/);
  assert.deepEqual(aviso.mentions, ["444@lid", "555@s.whatsapp.net"]);
  await run("111@lid", "plantilla", "", false);
  assert.match(ultimo(), /📝 \*Para publicar, este formato:\*\n#vendo qué es · precio · zona/);
  await run("111@lid", "plantilla", "set #vendo artículo | precio | barrio | foto", true);
  await run("111@lid", "plantilla", "", false);
  assert.match(ultimo(), /#vendo artículo \| precio \| barrio \| foto/);
  await run("111@lid", "reglas", "borrar", true);
  assert.equal(Reg.avisoReglasParaNuevos(G, ["444@lid"]), null);
  await run("111@lid", "reglas", "", false);
  assert.match(ultimo(), /no tiene reglas cargadas/);
});

test("compraventa: el horario del grupo cierra y abre solo", async () => {
  const cambios = [];
  const cliente2 = { ...cliente(), groupSettingUpdate: async (jid, estado) => cambios.push([jid, estado]) };
  const HGp = (await import("../plugins/grupo-horario.js")).default;
  const en = (h, min = 0) => new Date(2026, 8, 5, h, min);
  await HGp.run(msg("111@lid", ""), { client: cliente2, text: "" });
  assert.match(ultimo(), /no tiene horario/);
  await HGp.run(msg("111@lid", "a la noche"), { client: cliente2, text: "a la noche" });
  assert.match(ultimo(), /No entendí el horario/);
  assert.ok(HG.fijarHorarioGrupo(G, "8:00-22:00").ok);
  assert.equal(F.getChat(G).horarioGrupo, "08:00-22:00");
  assert.equal(await HG.chequearHorariosGrupo(en(23), cliente2), 1);
  assert.deepEqual(cambios, [[G, "announcement"]]);
  assert.equal(F.getChat(G).grupoCerradoPorHorario, 1);
  assert.match(ultimo(), /🌙 Grupo cerrado hasta las 08:00/);
  assert.equal(await HG.chequearHorariosGrupo(en(23, 30), cliente2), 0, "no repite el cierre");
  assert.equal(await HG.chequearHorariosGrupo(en(9), cliente2), 1);
  assert.deepEqual(cambios.at(-1), [G, "not_announcement"]);
  assert.match(ultimo(), /☀️ Grupo abierto\. Horario: de 08:00 a 22:00/);
  assert.equal(F.getChat(G).grupoCerradoPorHorario, 0);
  assert.equal(await HG.chequearHorariosGrupo(en(12), cliente2), 0);
  await HG.chequearHorariosGrupo(en(2), cliente2);
  assert.equal(F.getChat(G).grupoCerradoPorHorario, 1);
  await HG.quitarHorarioGrupo(G, cliente2);
  assert.deepEqual(cambios.at(-1), [G, "not_announcement"]);
  assert.deepEqual([F.getChat(G).horarioGrupo, F.getChat(G).grupoCerradoPorHorario], ["", 0]);
  assert.match(HG.textoHorarioGrupo(G), /no tiene horario/);
});

test("compraventa: los admins corrigen calificaciones maliciosas", async () => {
  const run = (sender, text, extra = {}) => Cal.run(msg(sender, text), { client: cliente(), command: "calificaciones", args: text.trim() ? text.trim().split(/\s+/) : [], text, isAdmin: false, isOwner: false, ...extra });
  // 111 tiene dos calificaciones de este grupo (de 222 y 333); una tercera hecha en otro grupo
  const otra = F.guardarCalificacion("otro@g.us", "444@lid", "111@lid", 1, "estafador", 0);
  assert.equal(otra.actualizada, false);
  await run("222@lid", "@111");
  const lista = ultimo();
  assert.match(lista, /⭐ Calificaciones de @111 \(3, promedio 2,7 de 5 \(3 calificaciones\)\):/);
  assert.match(lista, /\*#3\* ⭐ "estafador" — @444 · hace .* · en otro grupo/);
  assert.match(lista, /\*#2\* ⭐⭐ "me arrepentí" — @333/);
  assert.match(lista, /Admins: \.calificaciones borrar N/);
  // alguien común no puede borrar la de otro
  await run("222@lid", "borrar 2");
  assert.match(ultimo(), /Solo un admin del grupo, quien la hizo, o el owner puede borrar/);
  // un admin de este grupo no toca la que se hizo en otro grupo
  await run("222@lid", "borrar 3", { isAdmin: true });
  assert.match(ultimo(), /La #3 se hizo en otro grupo/);
  // ... pero sí edita y borra las de acá
  await run("222@lid", "editar 2 4 se arregló", { isAdmin: true });
  assert.match(ultimo(), /✏️ La calificación #2 de @333 a @111 quedó en ⭐⭐⭐⭐ "se arregló"\. @111 ahora tiene 3,3 de 5/);
  assert.deepEqual([F.getCalificacion(2).estrellas, F.getCalificacion(2).comentario], [4, "se arregló"]);
  await run("222@lid", "editar 2 9", { isAdmin: true });
  assert.match(ultimo(), /van de 1 a 5/);
  await run("222@lid", "borrar 99", { isAdmin: true });
  assert.match(ultimo(), /No hay ninguna calificación #99/);
  await run("222@lid", "borrar x", { isAdmin: true });
  assert.match(ultimo(), /¿Cuál\? Poné el número/);
  // el owner puede con la de otro grupo
  await run("222@lid", "borrar 3", { isOwner: true });
  assert.match(ultimo(), /🗑️ Borré la calificación #3 \(⭐ de @444 a @111\)\. @111 ahora tiene 4,5 de 5 \(2 calificaciones\)/);
  assert.equal(F.getCalificacion(3), null);
  // quien la hizo puede borrar la suya
  await run("333@lid", "borrar 2");
  assert.match(ultimo(), /Borré la calificación #2/);
  await run("333@lid", "borrar 1");
  assert.match(ultimo(), /Solo un admin del grupo/);
  await run("111@lid", "");
  assert.match(ultimo(), /⭐ Tus calificaciones \(1, promedio 5,0 de 5/);
});
