// Banco de preguntas de respaldo para la trivia, para cuando la IA no responde. Sin repetidas; las opciones van sin la
// letra adelante, la lib la pone al mostrar. "correcta" es la letra en minúscula.
export const BANCO = [
  { pregunta: "¿Cuál es la capital de Japón?", opciones: ["Osaka","Kioto","Tokio","Hiroshima"], correcta: "c" },
  { pregunta: "¿Qué animal puede vivir sin agua durante más tiempo?", opciones: ["Camello","Rata canguro","Tortuga del desierto","Koala"], correcta: "b" },
  { pregunta: "¿Cuál de las siguientes opciones es un sistema operativo?", opciones: ["Word","Windows","Chrome","Photoshop"], correcta: "b" },
  { pregunta: "¿Cuál es la capital de Suiza?", opciones: ["Zúrich","Ginebra","Basilea","Berna"], correcta: "d" },
  { pregunta: "¿Qué animal tiene la mordida más fuerte del mundo?", opciones: ["Tiburón blanco","León","Cocodrilo de agua salada","Hipopótamo"], correcta: "c" },
  { pregunta: "¿Cuál de las siguientes opciones es un navegador web?", opciones: ["Excel","Outlook","Firefox","PowerPoint"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Egipto?", opciones: ["El Cairo","Alejandría","Luxor","Asuán"], correcta: "a" },
  { pregunta: "¿Cuál es el animal terrestre más rápido del mundo?", opciones: ["León","Guepardo","Tigre","Antílope"], correcta: "b" },
  { pregunta: "¿En qué año se fundó Google?", opciones: ["1996","1998","2000","2002"], correcta: "b" },
  { pregunta: "¿Cuál es la capital de Brasil?", opciones: ["Río de Janeiro","São Paulo","Brasilia","Salvador"], correcta: "c" },
  { pregunta: "¿Qué animal puede regenerar su hígado?", opciones: ["Lagarto","Humano","Salamandra","Estrella de mar"], correcta: "b" },
  { pregunta: "¿Cuál de las siguientes redes sociales se centra en compartir fotos?", opciones: ["Twitter","LinkedIn","Instagram","WhatsApp"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Canadá?", opciones: ["Toronto","Montreal","Ottawa","Vancouver"], correcta: "c" },
  { pregunta: "¿Cuántos corazones tiene un pulpo?", opciones: ["1","2","3","4"], correcta: "c" },
  { pregunta: "¿Qué empresa desarrolló el sistema operativo Windows?", opciones: ["Apple","IBM","Microsoft","Google"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Turquía?", opciones: ["Estambul","Ankara","Esmirna","Antalya"], correcta: "b" },
  { pregunta: "¿Cuál es el único mamífero que puede volar?", opciones: ["Ardilla voladora","Murciélago","Lémur volador","Colibrí"], correcta: "b" },
  { pregunta: "¿Cuál de las siguientes opciones es un dispositivo de almacenamiento?", opciones: ["Teclado","Monitor","Disco duro","Impresora"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Nueva Zelanda?", opciones: ["Auckland","Wellington","Christchurch","Queenstown"], correcta: "b" },
  { pregunta: "¿Qué animal tiene la lengua más larga en relación a su tamaño?", opciones: ["Jirafa","Camaleón","Oso hormiguero","Rana"], correcta: "b" },
  { pregunta: "¿Cuál de las siguientes opciones es una aplicación de mensajería instantánea?", opciones: ["Excel","WhatsApp","Photoshop","PowerPoint"], correcta: "b" },
  { pregunta: "¿Cuál es la capital de Marruecos?", opciones: ["Casablanca","Marrakech","Rabat","Tánger"], correcta: "c" },
  { pregunta: "¿Qué animal duerme de pie?", opciones: ["Jirafa","Elefante","Caballo","Flamenco"], correcta: "c" },
  { pregunta: "¿Qué es Wi-Fi?", opciones: ["Un tipo de cable de internet","Una tecnología de conexión inalámbrica","Un navegador web","Un tipo de teléfono móvil"], correcta: "b" },
  { pregunta: "¿Cuál es la capital de Finlandia?", opciones: ["Oslo","Helsinki","Estocolmo","Copenhague"], correcta: "b" },
  { pregunta: "¿Cuál es el animal más grande del mundo?", opciones: ["Elefante africano","Tiburón ballena","Ballena azul","Jirafa"], correcta: "c" },
  { pregunta: "¿Cuál de las siguientes opciones es un lenguaje de programación?", opciones: ["HTML","HTTP","WWW","URL"], correcta: "a" },
  { pregunta: "¿Cuál es la capital de Argentina?", opciones: ["Buenos Aires","Córdoba","Rosario","Mendoza"], correcta: "a" },
  { pregunta: "¿Cuál es el animal nacional de Australia?", opciones: ["Koala","Canguro","Emú","Ornitorrinco"], correcta: "b" },
  { pregunta: "¿Cuál de las siguientes opciones es un motor de búsqueda?", opciones: ["Firefox","Google","Windows","Office"], correcta: "b" },
  { pregunta: "¿Cuál es la capital de Tailandia?", opciones: ["Phuket","Chiang Mai","Bangkok","Pattaya"], correcta: "c" },
  { pregunta: "¿Qué animal puede girar su cabeza 270 grados?", opciones: ["Búho","Camaleón","Halcón","Murciélago"], correcta: "a" },
  { pregunta: "¿Qué dispositivo se utiliza principalmente para introducir texto en una computadora?", opciones: ["Mouse","Monitor","Teclado","Impresora"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Irlanda?", opciones: ["Cork","Galway","Belfast","Dublín"], correcta: "d" },
  { pregunta: "¿Cuál es el único felino que no puede retraer sus garras?", opciones: ["Tigre","Leopardo","Guepardo","Jaguar"], correcta: "c" },
  { pregunta: "¿Cuál de las siguientes opciones es una plataforma de videos en línea?", opciones: ["Instagram","Twitter","YouTube","LinkedIn"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Portugal?", opciones: ["Oporto","Lisboa","Faro","Coímbra"], correcta: "b" },
  { pregunta: "¿Cuál es el animal más venenoso del mundo?", opciones: ["Serpiente mamba negra","Araña de rincón","Medusa de caja","Escorpión"], correcta: "c" },
  { pregunta: "¿Qué tipo de archivo se utiliza comúnmente para las fotos digitales?", opciones: ["DOC","PDF","JPG","MP3"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Grecia?", opciones: ["Atenas","Tesalónica","Patras","Heraklion"], correcta: "a" },
  { pregunta: "¿Qué animal puede sobrevivir sin cabeza durante semanas?", opciones: ["Cucaracha","Araña","Hormiga","Mosca"], correcta: "a" },
  { pregunta: "¿Cuál de las siguientes opciones es un servicio de correo electrónico?", opciones: ["WhatsApp","Gmail","Facebook","TikTok"], correcta: "b" },
  { pregunta: "¿Cuál es la capital de Noruega?", opciones: ["Bergen","Trondheim","Oslo","Stavanger"], correcta: "c" },
  { pregunta: "¿Cuál es el único mamífero que no puede saltar?", opciones: ["Rinoceronte","Elefante","Hipopótamo","Perezoso"], correcta: "b" },
  { pregunta: "¿Cuál de las siguientes opciones es un sistema operativo para dispositivos móviles?", opciones: ["Windows","Linux","Android","MacOS"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Australia?", opciones: ["Sydney","Melbourne","Brisbane","Canberra"], correcta: "d" },
  { pregunta: "¿Qué animal tiene el corazón proporcionalmente más grande?", opciones: ["Colibrí","Ballena","Elefante","Ratón"], correcta: "a" },
  { pregunta: "¿Qué dispositivo se utiliza para mostrar información visual en una computadora?", opciones: ["Teclado","Mouse","Monitor","Impresora"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Sudáfrica?", opciones: ["Johannesburgo","Ciudad del Cabo","Pretoria","Durban"], correcta: "c" },
  { pregunta: "¿Cuántos años puede vivir una tortuga gigante?", opciones: ["Hasta 50 años","Hasta 100 años","Hasta 150 años","Más de 200 años"], correcta: "d" },
  { pregunta: "¿Cuál es la capital de México?", opciones: ["Guadalajara","Monterrey","Ciudad de México","Cancún"], correcta: "c" },
  { pregunta: "¿Qué animal es conocido como el 'rey de la selva'?", opciones: ["Tigre","León","Leopardo","Jaguar"], correcta: "b" },
  { pregunta: "¿Cuál de las siguientes opciones es un programa de edición de imágenes?", opciones: ["Excel","Word","Photoshop","PowerPoint"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Francia?", opciones: ["Londres","Berlín","Madrid","París"], correcta: "d" },
  { pregunta: "¿Qué animal es el más grande de la familia de los felinos?", opciones: ["León","Leopardo","Tigre","Puma"], correcta: "c" },
  { pregunta: "¿Cuál de las siguientes opciones es una marca de teléfonos móviles?", opciones: ["Toyota","Samsung","Nike","Coca-Cola"], correcta: "b" },
  { pregunta: "¿Cuál es la capital de Italia?", opciones: ["Milán","Venecia","Roma","Nápoles"], correcta: "c" },
  { pregunta: "¿Qué animal es conocido por su capacidad de cambiar de color?", opciones: ["Camaleón","Cebra","Jirafa","Koala"], correcta: "a" },
  { pregunta: "¿Cuál de las siguientes opciones es una unidad de almacenamiento?", opciones: ["Megabyte","Kilogramo","Litro","Kilómetro"], correcta: "a" },
  { pregunta: "¿Cuál es la capital de China?", opciones: ["Shanghái","Hong Kong","Pekín","Cantón"], correcta: "c" },
  { pregunta: "¿Qué animal es conocido como el mejor amigo del hombre?", opciones: ["Gato","Perro","Hámster","Loro"], correcta: "b" },
  { pregunta: "¿Cuál de las siguientes opciones es un tipo de conexión a internet?", opciones: ["USB","HDMI","Wi-Fi","Bluetooth"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Rusia?", opciones: ["San Petersburgo","Kiev","Moscú","Vladivostok"], correcta: "c" },
  { pregunta: "¿Qué animal es conocido por dormir colgado boca abajo?", opciones: ["Koala","Perezoso","Murciélago","Orangután"], correcta: "c" },
  { pregunta: "¿Cuál de las siguientes opciones es un tipo de impresora?", opciones: ["Láser","Microondas","Licuadora","Tostadora"], correcta: "a" },
  { pregunta: "¿Cuál es la capital de España?", opciones: ["Barcelona","Sevilla","Valencia","Madrid"], correcta: "d" },
  { pregunta: "¿Qué animal es conocido por su trompa larga?", opciones: ["Rinoceronte","Hipopótamo","Elefante","Jirafa"], correcta: "c" },
  { pregunta: "¿Cuál de las siguientes opciones es un tipo de archivo de video?", opciones: ["JPG","MP4","PDF","TXT"], correcta: "b" },
  { pregunta: "¿Cuál es la capital de India?", opciones: ["Mumbai","Nueva Delhi","Calcuta","Bangalore"], correcta: "b" },
  { pregunta: "¿Qué animal es conocido por su caparazón?", opciones: ["Tortuga","Leopardo","Pingüino","Canguro"], correcta: "a" },
  { pregunta: "¿Cuál de las siguientes opciones es una red social profesional?", opciones: ["Facebook","Instagram","LinkedIn","TikTok"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Alemania?", opciones: ["Múnich","Hamburgo","Frankfurt","Berlín"], correcta: "d" },
  { pregunta: "¿Qué animal es conocido por su melena?", opciones: ["Tigre","León","Leopardo","Guepardo"], correcta: "b" },
  { pregunta: "¿Cuál de las siguientes opciones es un tipo de pantalla?", opciones: ["LED","USB","RAM","CPU"], correcta: "a" },
  { pregunta: "¿Qué animal es conocido por su joroba?", opciones: ["Elefante","Jirafa","Camello","Cebra"], correcta: "c" },
  { pregunta: "¿Cuál de las siguientes opciones es un sistema de posicionamiento global?", opciones: ["USB","HDMI","GPS","WIFI"], correcta: "c" },
  { pregunta: "¿Qué animal es conocido por su capacidad de regenerar su cola?", opciones: ["Iguana","Salamandra","Lagartija","Cocodrilo"], correcta: "c" },
  { pregunta: "¿Cuál de las siguientes opciones es un tipo de memoria de computadora?", opciones: ["HDD","RAM","USB","HDMI"], correcta: "b" },
  { pregunta: "¿Qué animal es conocido por su capacidad de volar hacia atrás?", opciones: ["Águila","Colibrí","Murciélago","Búho"], correcta: "b" },
  { pregunta: "¿Cuál de las siguientes opciones es un tipo de conexión para auriculares?", opciones: ["HDMI","VGA","Jack 3.5mm","USB"], correcta: "c" },
  { pregunta: "¿Qué animal es conocido por su veneno mortal?", opciones: ["Cobra real","Tortuga","Delfín","Pingüino"], correcta: "a" },
  { pregunta: "¿Cuál de las siguientes opciones es un programa de hojas de cálculo?", opciones: ["Word","PowerPoint","Excel","Paint"], correcta: "c" },
  { pregunta: "¿Qué animal es conocido por su capacidad de camuflaje?", opciones: ["León","Elefante","Pulpo","Jirafa"], correcta: "c" },
  { pregunta: "¿Cuál de las siguientes opciones es un tipo de batería recargable?", opciones: ["Alcalina","Litio","Zinc-carbono","Mercurio"], correcta: "b" },
  { pregunta: "¿Qué animal es conocido por su capacidad de producir luz?", opciones: ["Delfín","Luciérnaga","Cocodrilo","Pingüino"], correcta: "b" },
  { pregunta: "¿Cuál de las siguientes opciones es un tipo de puerto USB?", opciones: ["USB-A","USB-Z","USB-X","USB-Y"], correcta: "a" },
  { pregunta: "¿Qué animal es conocido por su capacidad de saltar muy alto?", opciones: ["Elefante","Canguro","Hipopótamo","Rinoceronte"], correcta: "b" },
  { pregunta: "¿Cuál de las siguientes opciones es un tipo de nube de almacenamiento en línea?", opciones: ["iCloud","Raincloud","Stormcloud","Skycloud"], correcta: "a" },
  { pregunta: "¿Cuál es la capital de Corea del Sur?", opciones: ["Busan","Incheon","Daegu","Seúl"], correcta: "d" },
  { pregunta: "¿Qué animal es conocido por su capacidad de regenerar sus extremidades?", opciones: ["Estrella de mar","Tiburón","Delfín","Ballena"], correcta: "a" },
  { pregunta: "¿Cuál de las siguientes opciones es un tipo de tarjeta de memoria?", opciones: ["SD","HD","CD","MD"], correcta: "a" },
  { pregunta: "¿Cuál es la capital de Suecia?", opciones: ["Gotemburgo","Malmö","Estocolmo","Uppsala"], correcta: "c" },
  { pregunta: "¿Qué animal es conocido por su capacidad de correr sobre el agua?", opciones: ["Pez volador","Lagarto basilisco","Pingüino","Delfín"], correcta: "b" },
  { pregunta: "¿Cuál de las siguientes opciones es un tipo de conexión inalámbrica para dispositivos cercanos?", opciones: ["Wi-Fi","5G","Bluetooth","NFC"], correcta: "c" },
];
