// Trivia: one question with four options, one try per person, and the first to get it right gets paid. Used by
// .trivia (on demand) and by lightning trivia (which fires on its own, see trivia-relampago.js). The questions are
// generated by the AI; if it doesn't answer, they come from the bank. You reply with the letter, quoting the question
// or loose in the chat, and the option's text works too.
import { preguntarIA } from "./ia.js";
import { elegirAlAzar } from "./azar.js";
import { BANCO } from "./trivia-banco.js";

export const TRIVIA = {
  SEGUNDOS: 30, // how long a .trivia round lasts
  RECIENTES: 25, // questions remembered per group so they aren't repeated
  RESERVA_MS: 60 * 1000, // how long a round may take to set up before the turn is released
};
const LETRAS = ["a", "b", "c", "d"];
const TEMAS = ["geografía", "historia", "ciencia", "cine y series", "música", "deportes", "Uruguay", "comida", "tecnología", "animales", "literatura", "cultura pop"];
const ESQUEMA = {
  type: "object",
  properties: {
    pregunta: { type: "string" },
    opciones: { type: "array", items: { type: "string" } },
    correcta: { type: "string", enum: ["A", "B", "C", "D"] },
  },
  required: ["pregunta", "opciones", "correcta"],
};

if (!globalThis.rondasTrivia) globalThis.rondasTrivia = new Map(); // chat -> ronda abierta
const recientes = new Map(); // chat -> the latest questions asked

export const normalizar = (t) =>
  String(t || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .trim();

const recordar = (chat, pregunta) => {
  const lista = recientes.get(chat) || [];
  lista.push(pregunta);
  if (lista.length > TRIVIA.RECIENTES) lista.shift();
  recientes.set(chat, lista);
};

// A fresh question for the group: from the AI when it answers properly, otherwise from the bank, and in both cases
// without repeating the latest ones.
export async function generarPregunta(chat) {
  const hechas = recientes.get(chat) || [];
  if (globalThis.geminiApiKey) {
    const tema = elegirAlAzar(TEMAS);
    const r = await preguntarIA(`Escribí UNA pregunta de trivia de ${tema}, de dificultad media, con exactamente 4 opciones cortas y una sola correcta. Respondé solo con los campos "pregunta", "opciones" (los 4 textos, sin letra adelante) y "correcta" (A, B, C o D).`, { schema: ESQUEMA }).catch(() => ({ ok: false }));
    if (r.ok) {
      try {
        const d = JSON.parse(r.texto);
        if (d.pregunta && Array.isArray(d.opciones) && d.opciones.length === 4 && /^[ABCD]$/.test(d.correcta) && !hechas.includes(String(d.pregunta).trim())) {
          return { pregunta: String(d.pregunta).trim(), opciones: d.opciones.map((o) => String(o).trim()), correcta: d.correcta.toLowerCase() };
        }
      } catch {}
    }
  }
  const candidatas = BANCO.filter((p) => !hechas.includes(p.pregunta));
  return elegirAlAzar(candidatas.length ? candidatas : BANCO);
}

export const rondaDe = (chat) => globalThis.rondasTrivia.get(chat) || null;

// Holds the chat's turn while the question is generated (the AI takes a while), so two trivias can't open at once.
// Returns false if there is already a round or a hold. The hold releases itself if whoever took it never opens the round.
export function reservarRonda(chat, tipo) {
  if (globalThis.rondasTrivia.has(chat)) return false;
  const reserva = { tipo, reservada: true, vence: Date.now() + TRIVIA.RESERVA_MS, intentos: new Set(), timeout: null };
  reserva.timeout = setTimeout(() => {
    if (globalThis.rondasTrivia.get(chat) === reserva) globalThis.rondasTrivia.delete(chat);
  }, TRIVIA.RESERVA_MS);
  globalThis.rondasTrivia.set(chat, reserva);
  return true;
}
export function liberarRonda(chat) {
  const r = rondaDe(chat);
  if (!r?.reservada) return false;
  clearTimeout(r.timeout);
  globalThis.rondasTrivia.delete(chat);
  return true;
}
export const segundosRestantes = (ronda) => Math.max(0, Math.ceil((ronda.vence - Date.now()) / 1000));
const textoCorrecta = (p) => `${p.correcta.toUpperCase()}) ${p.opciones[LETRAS.indexOf(p.correcta)]}`;

export function textoPregunta({ titulo, premio, pregunta, segundos }) {
  const cabecera = premio ? `${titulo} — ${premio} UruCoins para el primero que acierte` : titulo;
  const opciones = pregunta.opciones.map((o, i) => `${LETRAS[i].toUpperCase()}) ${o}`).join("\n");
  return `${cabecera}\n\n${pregunta.pregunta}\n${opciones}\n\n_Respondé con la letra, citando este mensaje o suelta en el chat. ${segundos} segundos y un solo intento por persona._`;
}

// Opens the group's round. alGanar(lid) and alVencer() may return extra text for the closing message (prize, bets).
// Returns the round.
export function abrirRonda(chat, { tipo, pregunta, mensajeId, segundos, client, alGanar = null, alVencer = null }) {
  liberarRonda(chat); // the hold, if there was one, is taken over by this round
  const ronda = { tipo, pregunta, mensajeId, intentos: new Set(), vence: Date.now() + segundos * 1000, alGanar, alVencer, timeout: null };
  ronda.timeout = setTimeout(() => {
    if (globalThis.rondasTrivia.get(chat) !== ronda) return;
    globalThis.rondasTrivia.delete(chat);
    client.sendMessage(chat, { text: pegar(`⏳ Nadie acertó. Era *${textoCorrecta(pregunta)}*.`, alVencer?.()) }).catch(console.error);
  }, segundos * 1000);
  globalThis.rondasTrivia.set(chat, ronda);
  recordar(chat, pregunta.pregunta);
  return ronda;
}

const pegar = (base, extra) => (extra ? `${base}${extra.startsWith("\n") ? "" : "\n"}${extra}` : base);

// Which letter they meant: "c", "C)", "(c)", "opción c", "c) tokio" or the option's text. null if it isn't an answer.
export function parsearRespuesta(texto, opciones) {
  const t = normalizar(texto);
  if (!t) return null;
  const letra = t.match(/^(?:opcion )?([abcd])(?: .+)?$/);
  if (letra) return letra[1];
  const i = opciones.findIndex((o) => normalizar(o) === t);
  return i >= 0 ? LETRAS[i] : null;
}

// Called on every message. Returns { reaccion, texto?, mentions? } if the message was an answer to the chat's open
// round, and null if there was no round or the message wasn't an answer.
export function responderTrivia(m) {
  const ronda = rondaDe(m.chat);
  if (!ronda || ronda.reservada) return null;
  if (m.quoted?.id && m.quoted.id !== ronda.mensajeId) return null; // it quotes something else, not the trivia
  const letra = parsearRespuesta(m.text, ronda.pregunta.opciones);
  if (!letra) return null;
  if (ronda.intentos.has(m.sender)) return { reaccion: "🙅" };
  ronda.intentos.add(m.sender);
  if (letra !== ronda.pregunta.correcta) return { reaccion: "❌" };
  clearTimeout(ronda.timeout);
  globalThis.rondasTrivia.delete(m.chat);
  const texto = pegar(`✅ ¡Acertó @${m.sender.split("@")[0]}! Era *${textoCorrecta(ronda.pregunta)}*.`, ronda.alGanar?.(m.sender));
  return { reaccion: "✅", texto, mentions: [m.sender] };
}

// For the tests and for .trivia when the game is cut short from outside.
export function cerrarRonda(chat) {
  const ronda = rondaDe(chat);
  if (!ronda) return false;
  clearTimeout(ronda.timeout);
  globalThis.rondasTrivia.delete(chat);
  return true;
}
