// Banco de preguntas de respaldo para la trivia, para cuando la IA no responde. Dificultad media, temas variados y
// bastante de Uruguay y el Río de la Plata. Las opciones van sin la letra adelante, la lib la pone al mostrar;
// "correcta" es la letra en minúscula. La posición de la correcta se reparte con un hash de la pregunta.
export const BANCO = [
  { pregunta: "¿Cuántos departamentos tiene Uruguay?", opciones: ["17","21","19","23"], correcta: "c" },
  { pregunta: "¿Cuál es el departamento más grande de Uruguay?", opciones: ["Salto","Cerro Largo","Durazno","Tacuarembó"], correcta: "d" },
  { pregunta: "¿Cuál es el punto más alto de Uruguay?", opciones: ["Cerro de Montevideo","Cerro Pan de Azúcar","Cerro Batoví","Cerro Catedral"], correcta: "d" },
  { pregunta: "¿Cuál es la capital del departamento de Río Negro?", opciones: ["Young","Fray Bentos","Mercedes","Paysandú"], correcta: "b" },
  { pregunta: "¿Cuál es la capital del departamento de Soriano?", opciones: ["Dolores","Cardona","Mercedes","Trinidad"], correcta: "c" },
  { pregunta: "¿Cuál es la capital del departamento de Cerro Largo?", opciones: ["Río Branco","Treinta y Tres","Rivera","Melo"], correcta: "d" },
  { pregunta: "¿Cuál es la capital del departamento de Lavalleja?", opciones: ["Minas","José Pedro Varela","Solís de Mataojo","Florida"], correcta: "a" },
  { pregunta: "¿Cuál es la capital del departamento de Flores?", opciones: ["Durazno","Florida","Ismael Cortinas","Trinidad"], correcta: "d" },
  { pregunta: "¿En qué departamento está Cabo Polonio?", opciones: ["Maldonado","Canelones","Rocha","Treinta y Tres"], correcta: "c" },
  { pregunta: "¿En qué departamento están las Termas del Daymán?", opciones: ["Paysandú","Artigas","Río Negro","Salto"], correcta: "d" },
  { pregunta: "¿Quién fundó Piriápolis?", opciones: ["Bruno Mauricio de Zabala","Francisco Piria","Manuel Lobo","Juan Manuel Blanes"], correcta: "b" },
  { pregunta: "¿Quién fundó Montevideo?", opciones: ["Manuel Lobo","Bruno Mauricio de Zabala","José Artigas","Pedro de Mendoza"], correcta: "b" },
  { pregunta: "¿Qué ciudad uruguaya fundaron los portugueses en 1680?", opciones: ["Maldonado","Montevideo","Paysandú","Colonia del Sacramento"], correcta: "d" },
  { pregunta: "¿Cuál es la laguna más grande de Uruguay?", opciones: ["Laguna Merín","Laguna Negra","Laguna del Sauce","Laguna de Rocha"], correcta: "a" },
  { pregunta: "¿Qué río atraviesa Uruguay de este a oeste y desemboca en el río Uruguay?", opciones: ["Río Santa Lucía","Río Yí","Río Cebollatí","Río Negro"], correcta: "d" },
  { pregunta: "¿Qué represa comparte Uruguay con Argentina?", opciones: ["Rincón del Bonete","Baygorria","Palmar","Salto Grande"], correcta: "d" },
  { pregunta: "¿Qué ruta une Montevideo con Colonia del Sacramento?", opciones: ["Ruta 1","Ruta 5","Ruta 8","Ruta 9"], correcta: "a" },
  { pregunta: "¿Qué ruta une Montevideo con Rivera?", opciones: ["Ruta 5","Ruta 3","Ruta 1","Ruta 9"], correcta: "a" },
  { pregunta: "¿En qué ciudad está el Frigorífico Anglo, patrimonio de la humanidad?", opciones: ["Salto","Colonia del Sacramento","Fray Bentos","Mercedes"], correcta: "c" },
  { pregunta: "¿Qué fecha se recuerda cada 25 de agosto en Uruguay?", opciones: ["La Declaratoria de la Independencia","La Jura de la Constitución","El natalicio de Artigas","El desembarco de los Treinta y Tres"], correcta: "a" },
  { pregunta: "¿Qué se celebra en Uruguay el 18 de julio?", opciones: ["La Declaratoria de la Independencia","La Jura de la Constitución","La Batalla de Las Piedras","El natalicio de Artigas"], correcta: "b" },
  { pregunta: "¿En qué año se juró la primera Constitución uruguaya?", opciones: ["1825","1830","1811","1842"], correcta: "b" },
  { pregunta: "¿En qué país murió José Artigas?", opciones: ["Uruguay","Argentina","Brasil","Paraguay"], correcta: "d" },
  { pregunta: "¿Quién fue el primer presidente constitucional de Uruguay?", opciones: ["Manuel Oribe","Juan Antonio Lavalleja","Fructuoso Rivera","José Artigas"], correcta: "c" },
  { pregunta: "¿Quién encabezó a los Treinta y Tres Orientales?", opciones: ["Fructuoso Rivera","Manuel Oribe","Juan Antonio Lavalleja","José Artigas"], correcta: "c" },
  { pregunta: "¿En qué playa desembarcaron los Treinta y Tres Orientales en 1825?", opciones: ["Playa Ramírez","Playa de los Pocitos","Playa de la Agraciada","Playa Mansa"], correcta: "c" },
  { pregunta: "¿En qué año fue la Batalla de Las Piedras?", opciones: ["1811","1825","1830","1843"], correcta: "a" },
  { pregunta: "¿Qué presidente uruguayo impulsó la ley de las ocho horas de trabajo, en 1915?", opciones: ["Fructuoso Rivera","Gabriel Terra","Baltasar Brum","José Batlle y Ordóñez"], correcta: "d" },
  { pregunta: "¿En qué localidad uruguaya votaron mujeres por primera vez en Sudamérica, en 1927?", opciones: ["Cerro Chato","Florida","Durazno","Melo"], correcta: "a" },
  { pregunta: "¿Contra qué país pelearon Argentina, Brasil y Uruguay en la Guerra de la Triple Alianza?", opciones: ["Bolivia","Paraguay","Chile","Perú"], correcta: "b" },
  { pregunta: "¿Cuántas franjas tiene la bandera de Uruguay?", opciones: ["7","11","9","13"], correcta: "c" },
  { pregunta: "¿Quién escribió la letra del Himno Nacional uruguayo?", opciones: ["Francisco José Debali","Juan Zorrilla de San Martín","Bartolomé Hidalgo","Francisco Acuña de Figueroa"], correcta: "d" },
  { pregunta: "¿Cuál es el ave nacional de Uruguay?", opciones: ["Hornero","Tero","Ñandú","Cardenal"], correcta: "b" },
  { pregunta: "¿Cuál es la flor nacional de Uruguay?", opciones: ["Jacarandá","Ceibo","Margarita","Clavel"], correcta: "b" },
  { pregunta: "¿Qué árbol se conoce como \"el árbol de Artigas\"?", opciones: ["Ombú","Ceibo","Ibirapitá","Timbó"], correcta: "c" },
  { pregunta: "¿Cuál fue el primer país del mundo en legalizar la producción y venta de cannabis, en 2013?", opciones: ["Canadá","Uruguay","Países Bajos","Portugal"], correcta: "b" },
  { pregunta: "¿Qué país consume más yerba mate por habitante?", opciones: ["Argentina","Paraguay","Uruguay","Brasil"], correcta: "c" },
  { pregunta: "¿Cuántos habitantes tiene Uruguay, aproximadamente?", opciones: ["3,5 millones","1,5 millones","5 millones","8 millones"], correcta: "a" },
  { pregunta: "¿Cuál es el prefijo telefónico internacional de Uruguay?", opciones: ["+54","+595","+598","+591"], correcta: "c" },
  { pregunta: "¿En qué ciudad se dice que nació el chivito?", opciones: ["Montevideo","Colonia","Salto","Punta del Este"], correcta: "d" },
  { pregunta: "¿Qué lleva el \"medio y medio\" del Mercado del Puerto?", opciones: ["Cerveza y vino","Vino blanco y vino espumante","Caña y miel","Whisky y agua"], correcta: "b" },
  { pregunta: "¿Qué se come en Uruguay cuando llueve, según la tradición?", opciones: ["Chivito","Pastafrola","Bizcochos","Torta frita"], correcta: "d" },
  { pregunta: "¿De qué departamento es originario el postre chajá?", opciones: ["Salto","Paysandú","Montevideo","Colonia"], correcta: "b" },
  { pregunta: "¿Cuál es la uva emblemática del vino uruguayo?", opciones: ["Malbec","Merlot","Tannat","Cabernet Sauvignon"], correcta: "c" },
  { pregunta: "¿Cuáles son los tres tambores del candombe?", opciones: ["Bombo, redoblante y platillo","Chico, mediano y grande","Chico, repique y piano","Tumbadora, bongó y cajón"], correcta: "c" },
  { pregunta: "¿De qué barrios de Montevideo sale el Desfile de Llamadas?", opciones: ["Cordón y Centro","Barrio Sur y Palermo","Cerro y La Teja","Pocitos y Buceo"], correcta: "b" },
  { pregunta: "¿Quién compuso \"La cumparsita\"?", opciones: ["Gerardo Matos Rodríguez","Carlos Gardel","Astor Piazzolla","Francisco Canaro"], correcta: "a" },
  { pregunta: "¿Qué uruguayo ganó el Oscar a mejor canción con \"Al otro lado del río\"?", opciones: ["Jaime Roos","Rubén Rada","Fernando Cabrera","Jorge Drexler"], correcta: "d" },
  { pregunta: "¿Quién canta \"Brindis por Pierrot\"?", opciones: ["Alfredo Zitarrosa","Rubén Rada","Eduardo Mateo","Jaime Roos"], correcta: "d" },
  { pregunta: "¿Quién canta \"Doña Soledad\" y \"Adagio en mi país\"?", opciones: ["Daniel Viglietti","Jaime Roos","Alfredo Zitarrosa","Los Olimareños"], correcta: "c" },
  { pregunta: "¿Qué banda uruguaya canta \"Ya no sé qué hacer conmigo\"?", opciones: ["No Te Va Gustar","La Vela Puerca","Buitres","El Cuarteto de Nos"], correcta: "d" },
  { pregunta: "¿Quién escribió \"La tregua\"?", opciones: ["Juan Carlos Onetti","Eduardo Galeano","Mario Benedetti","Horacio Quiroga"], correcta: "c" },
  { pregunta: "¿Quién escribió \"Las venas abiertas de América Latina\"?", opciones: ["Mario Benedetti","Eduardo Galeano","Juan Carlos Onetti","Idea Vilariño"], correcta: "b" },
  { pregunta: "¿Quién escribió \"El astillero\"?", opciones: ["Mario Benedetti","Felisberto Hernández","Juan Carlos Onetti","Eduardo Galeano"], correcta: "c" },
  { pregunta: "¿Qué escritor nacido en Salto escribió \"Cuentos de la selva\"?", opciones: ["Juan Carlos Onetti","Enrique Amorim","Horacio Quiroga","Julio Herrera y Reissig"], correcta: "c" },
  { pregunta: "¿A qué poeta uruguaya la llamaron \"Juana de América\"?", opciones: ["Delmira Agustini","Juana de Ibarbourou","Idea Vilariño","Marosa di Giorgio"], correcta: "b" },
  { pregunta: "¿Qué pintor uruguayo dibujó \"América invertida\", el mapa con el sur arriba?", opciones: ["Pedro Figari","Joaquín Torres García","Juan Manuel Blanes","Carlos Páez Vilaró"], correcta: "b" },
  { pregunta: "¿Quién pintó \"El Juramento de los Treinta y Tres Orientales\"?", opciones: ["Juan Manuel Blanes","Pedro Figari","Joaquín Torres García","Rafael Barradas"], correcta: "a" },
  { pregunta: "¿En qué año se inauguró el Palacio Legislativo?", opciones: ["1925","1908","1930","1950"], correcta: "a" },
  { pregunta: "¿En qué año se inauguró el Estadio Centenario?", opciones: ["1924","1930","1950","1935"], correcta: "b" },
  { pregunta: "¿Contra quién ganó Uruguay la final del primer Mundial, en 1930?", opciones: ["Argentina","Brasil","Italia","Estados Unidos"], correcta: "a" },
  { pregunta: "¿Quién hizo el gol del triunfo en el Maracanazo de 1950?", opciones: ["Alcides Ghiggia","Juan Alberto Schiaffino","Obdulio Varela","Óscar Míguez"], correcta: "a" },
  { pregunta: "¿Quién fue el capitán de Uruguay en el Maracanazo?", opciones: ["Obdulio Varela","Alcides Ghiggia","Roque Máspoli","Juan Alberto Schiaffino"], correcta: "a" },
  { pregunta: "¿Cuántas Copas América tiene Uruguay?", opciones: ["10","12","17","15"], correcta: "d" },
  { pregunta: "¿En qué dos Juegos Olímpicos ganó Uruguay el oro en fútbol?", opciones: ["1924 y 1928","1920 y 1924","1928 y 1932","1948 y 1952"], correcta: "a" },
  { pregunta: "¿Cuántas Copas Libertadores ganó Peñarol?", opciones: ["3","4","6","5"], correcta: "d" },
  { pregunta: "¿Cuántas Copas Libertadores ganó Nacional?", opciones: ["2","4","5","3"], correcta: "d" },
  { pregunta: "¿En qué año se fundó Nacional?", opciones: ["1899","1891","1902","1910"], correcta: "a" },
  { pregunta: "¿Cómo se llama el estadio de Nacional?", opciones: ["Campeón del Siglo","Estadio Centenario","Gran Parque Central","Parque Viera"], correcta: "c" },
  { pregunta: "¿Qué uruguayo ganó el Balón de Oro del Mundial 2010?", opciones: ["Luis Suárez","Edinson Cavani","Diego Forlán","Diego Lugano"], correcta: "c" },
  { pregunta: "¿Cómo le dicen a Óscar Washington Tabárez?", opciones: ["El Pistolero","El Matador","El Tano","El Maestro"], correcta: "d" },
  { pregunta: "¿Qué ciclista uruguayo ganó una medalla de plata en Sídney 2000?", opciones: ["Milton Wynants","Federico Moreira","Jorge Soto","Andrés Silva"], correcta: "a" },
  { pregunta: "¿Cómo se llama la selección uruguaya de rugby?", opciones: ["Los Pumas","Los Teros","Los Cóndores","Los Charrúas"], correcta: "b" },
  { pregunta: "¿Qué actriz uruguaya protagonizó \"Muñeca brava\"?", opciones: ["Bárbara Mori","Araceli González","Natalia Oreiro","Florencia Peña"], correcta: "c" },
  { pregunta: "¿Cuál es el roedor más grande del mundo, común en Uruguay?", opciones: ["Nutria","Vizcacha","Cuis","Carpincho"], correcta: "d" },
  { pregunta: "¿Cuál es el ave más grande de América, presente en Uruguay?", opciones: ["Ñandú","Cóndor","Tero","Garza"], correcta: "a" },
  { pregunta: "¿Qué ballena visita cada año la costa de Rocha y Maldonado?", opciones: ["Ballena franca austral","Ballena azul","Cachalote","Ballena jorobada"], correcta: "a" },
  { pregunta: "¿Cuántas provincias tiene Argentina?", opciones: ["19","23","25","27"], correcta: "b" },
  { pregunta: "¿En qué ciudad nació el Che Guevara?", opciones: ["Buenos Aires","Córdoba","La Habana","Rosario"], correcta: "d" },
  { pregunta: "¿Quién creó a Mafalda?", opciones: ["Fontanarrosa","Liniers","Quino","Maitena"], correcta: "c" },
  { pregunta: "¿En qué año se independizó Argentina?", opciones: ["1810","1825","1830","1816"], correcta: "d" },
  { pregunta: "¿Cuál es la capital constitucional de Bolivia?", opciones: ["Sucre","La Paz","Santa Cruz","Cochabamba"], correcta: "a" },
  { pregunta: "¿En qué país sudamericano el idioma oficial es el neerlandés?", opciones: ["Guyana","Surinam","Guayana Francesa","Belice"], correcta: "b" },
  { pregunta: "¿Entre qué dos países están las Cataratas del Iguazú?", opciones: ["Argentina y Paraguay","Brasil y Paraguay","Argentina y Brasil","Brasil y Uruguay"], correcta: "c" },
  { pregunta: "¿En qué país está el Salar de Uyuni?", opciones: ["Bolivia","Chile","Perú","Argentina"], correcta: "a" },
  { pregunta: "¿A qué país pertenece la Isla de Pascua?", opciones: ["Perú","Ecuador","Chile","Francia"], correcta: "c" },
  { pregunta: "¿Cuál es la montaña más alta de América?", opciones: ["Aconcagua","Ojos del Salado","Huascarán","Chimborazo"], correcta: "a" },
  { pregunta: "¿En qué país está la catarata más alta del mundo, el Salto Ángel?", opciones: ["Venezuela","Brasil","Colombia","Guyana"], correcta: "a" },
  { pregunta: "¿Qué imperio construyó Machu Picchu?", opciones: ["Maya","Inca","Azteca","Olmeca"], correcta: "b" },
  { pregunta: "¿Cómo se llamaba la capital de los aztecas?", opciones: ["Cuzco","Tenochtitlan","Chichén Itzá","Teotihuacán"], correcta: "b" },
  { pregunta: "¿Qué escritor colombiano escribió \"Cien años de soledad\"?", opciones: ["Mario Vargas Llosa","Gabriel García Márquez","Julio Cortázar","Jorge Luis Borges"], correcta: "b" },
  { pregunta: "¿Quién escribió \"Rayuela\"?", opciones: ["Jorge Luis Borges","Ernesto Sabato","Adolfo Bioy Casares","Julio Cortázar"], correcta: "d" },
  { pregunta: "¿Quién escribió el \"Martín Fierro\"?", opciones: ["Domingo Faustino Sarmiento","Esteban Echeverría","Leopoldo Lugones","José Hernández"], correcta: "d" },
  { pregunta: "¿De qué país es Pablo Neruda?", opciones: ["Chile","Perú","Argentina","Colombia"], correcta: "a" },
  { pregunta: "¿Quién fue el cantante de Soda Stereo?", opciones: ["Charly García","Fito Páez","Andrés Calamaro","Gustavo Cerati"], correcta: "d" },
  { pregunta: "¿En qué ciudad nació Shakira?", opciones: ["Bogotá","Barranquilla","Medellín","Cartagena"], correcta: "b" },
  { pregunta: "¿De qué país es Bad Bunny?", opciones: ["República Dominicana","Puerto Rico","Colombia","México"], correcta: "b" },
  { pregunta: "¿Quién pintó \"Las dos Fridas\"?", opciones: ["Diego Rivera","Frida Kahlo","Fernando Botero","Remedios Varo"], correcta: "b" },
  { pregunta: "¿Quién creó al Chavo del 8?", opciones: ["Cantinflas","Eugenio Derbez","Chespirito","Pedro Infante"], correcta: "c" },
  { pregunta: "¿Qué película argentina ganó el Oscar a mejor película extranjera en 2010?", opciones: ["Relatos salvajes","Nueve reinas","La historia oficial","El secreto de sus ojos"], correcta: "d" },
  { pregunta: "¿Cuál es la capital de Suiza?", opciones: ["Zúrich","Berna","Ginebra","Basilea"], correcta: "b" },
  { pregunta: "¿Cuál es la capital de Australia?", opciones: ["Sídney","Melbourne","Canberra","Brisbane"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Canadá?", opciones: ["Toronto","Montreal","Ottawa","Vancouver"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Brasil?", opciones: ["Río de Janeiro","Brasilia","São Paulo","Salvador"], correcta: "b" },
  { pregunta: "¿Cuál es la capital de Turquía?", opciones: ["Estambul","Esmirna","Antalya","Ankara"], correcta: "d" },
  { pregunta: "¿Cuál es la capital de Nueva Zelanda?", opciones: ["Auckland","Wellington","Christchurch","Queenstown"], correcta: "b" },
  { pregunta: "¿Cuál es la capital de Marruecos?", opciones: ["Casablanca","Marrakech","Tánger","Rabat"], correcta: "d" },
  { pregunta: "¿Cuál es la capital administrativa de Sudáfrica?", opciones: ["Johannesburgo","Pretoria","Ciudad del Cabo","Durban"], correcta: "b" },
  { pregunta: "¿Cuál es la capital de Vietnam?", opciones: ["Hanói","Ciudad Ho Chi Minh","Da Nang","Hue"], correcta: "a" },
  { pregunta: "¿Cuál es la capital de Pakistán?", opciones: ["Karachi","Lahore","Islamabad","Peshawar"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Nigeria?", opciones: ["Abuya","Lagos","Kano","Ibadán"], correcta: "a" },
  { pregunta: "¿Cuál es la capital de Kazajistán?", opciones: ["Almatý","Taskent","Astaná","Biskek"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de Finlandia?", opciones: ["Helsinki","Oslo","Estocolmo","Copenhague"], correcta: "a" },
  { pregunta: "¿Cuál es la capital de Noruega?", opciones: ["Oslo","Bergen","Trondheim","Stavanger"], correcta: "a" },
  { pregunta: "¿Cuál es la capital de Suecia?", opciones: ["Estocolmo","Gotemburgo","Malmö","Uppsala"], correcta: "a" },
  { pregunta: "¿Cuál es la capital de Irlanda?", opciones: ["Belfast","Dublín","Cork","Galway"], correcta: "b" },
  { pregunta: "¿Cuál es la capital de Tailandia?", opciones: ["Bangkok","Phuket","Chiang Mai","Pattaya"], correcta: "a" },
  { pregunta: "¿Cuál es la capital de China?", opciones: ["Shanghái","Hong Kong","Pekín","Cantón"], correcta: "c" },
  { pregunta: "¿Cuál es la capital de India?", opciones: ["Nueva Delhi","Bombay","Calcuta","Bangalore"], correcta: "a" },
  { pregunta: "¿Cuál es la capital de Corea del Sur?", opciones: ["Busan","Seúl","Incheon","Pionyang"], correcta: "b" },
  { pregunta: "¿Cuál es el país más pequeño del mundo?", opciones: ["Vaticano","Mónaco","San Marino","Liechtenstein"], correcta: "a" },
  { pregunta: "¿Cuál es el país más grande del mundo?", opciones: ["Canadá","Rusia","China","Estados Unidos"], correcta: "b" },
  { pregunta: "¿Cuál es el país más poblado del mundo?", opciones: ["China","Estados Unidos","Indonesia","India"], correcta: "d" },
  { pregunta: "¿Cuál es el océano más grande?", opciones: ["Atlántico","Índico","Pacífico","Ártico"], correcta: "c" },
  { pregunta: "¿Cuál es el desierto cálido más grande del mundo?", opciones: ["Gobi","Sahara","Atacama","Kalahari"], correcta: "b" },
  { pregunta: "¿Cuál es el desierto más seco del mundo?", opciones: ["Atacama","Sahara","Gobi","Namib"], correcta: "a" },
  { pregunta: "¿Cuál es el río más caudaloso del mundo?", opciones: ["Amazonas","Nilo","Congo","Yangtsé"], correcta: "a" },
  { pregunta: "¿Qué lago navegable es el más alto del mundo?", opciones: ["Baikal","Titicaca","Victoria","Superior"], correcta: "b" },
  { pregunta: "¿Qué océanos une el Canal de Panamá?", opciones: ["Atlántico y Pacífico","Atlántico e Índico","Pacífico e Índico","Atlántico y Ártico"], correcta: "a" },
  { pregunta: "¿A qué país pertenece Groenlandia?", opciones: ["Noruega","Canadá","Islandia","Dinamarca"], correcta: "d" },
  { pregunta: "¿Cuál es la montaña más alta de África?", opciones: ["Monte Kenia","Kilimanjaro","Atlas","Monte Elgon"], correcta: "b" },
  { pregunta: "¿En qué país está el Taj Mahal?", opciones: ["Pakistán","India","Irán","Turquía"], correcta: "b" },
  { pregunta: "¿En qué país está la ciudad antigua de Petra?", opciones: ["Egipto","Israel","Jordania","Líbano"], correcta: "c" },
  { pregunta: "¿En qué país está el templo de Angkor Wat?", opciones: ["Tailandia","Vietnam","Camboya","Laos"], correcta: "c" },
  { pregunta: "¿Qué país le regaló la Estatua de la Libertad a Estados Unidos?", opciones: ["Reino Unido","Francia","España","Italia"], correcta: "b" },
  { pregunta: "¿Quién diseñó la Sagrada Familia de Barcelona?", opciones: ["Salvador Dalí","Santiago Calatrava","Antoni Gaudí","Pablo Picasso"], correcta: "c" },
  { pregunta: "¿En qué año se inauguró la Torre Eiffel?", opciones: ["1869","1900","1889","1925"], correcta: "c" },
  { pregunta: "¿En qué año llegó el ser humano a la Luna?", opciones: ["1959","1972","1969","1965"], correcta: "c" },
  { pregunta: "¿Quién fue la primera persona en viajar al espacio?", opciones: ["Neil Armstrong","John Glenn","Yuri Gagarin","Valentina Tereshkova"], correcta: "c" },
  { pregunta: "¿En qué año cayó el Muro de Berlín?", opciones: ["1991","1985","1979","1989"], correcta: "d" },
  { pregunta: "¿En qué año terminó la Segunda Guerra Mundial?", opciones: ["1944","1945","1946","1948"], correcta: "b" },
  { pregunta: "¿En qué año empezó la Primera Guerra Mundial?", opciones: ["1914","1912","1916","1918"], correcta: "a" },
  { pregunta: "¿En qué año se hundió el Titanic?", opciones: ["1905","1912","1920","1931"], correcta: "b" },
  { pregunta: "¿En qué año fue la Revolución Francesa?", opciones: ["1776","1789","1804","1815"], correcta: "b" },
  { pregunta: "¿En qué año fue la Revolución Rusa?", opciones: ["1905","1917","1922","1939"], correcta: "b" },
  { pregunta: "¿En qué año se fundó la ONU?", opciones: ["1919","1950","1945","1961"], correcta: "c" },
  { pregunta: "¿Qué país fue el primero en dar el voto a las mujeres, en 1893?", opciones: ["Reino Unido","Nueva Zelanda","Estados Unidos","Finlandia"], correcta: "b" },
  { pregunta: "¿Quién fue el primer emperador romano?", opciones: ["Julio César","Nerón","Trajano","Augusto"], correcta: "d" },
  { pregunta: "¿En qué batalla fue derrotado Napoleón definitivamente, en 1815?", opciones: ["Trafalgar","Austerlitz","Waterloo","Leipzig"], correcta: "c" },
  { pregunta: "¿Quién fue el primer presidente de Estados Unidos?", opciones: ["George Washington","Thomas Jefferson","Abraham Lincoln","Benjamin Franklin"], correcta: "a" },
  { pregunta: "¿Entre qué dos potencias se dio la Guerra Fría?", opciones: ["Estados Unidos y la Unión Soviética","Estados Unidos y China","Reino Unido y Alemania","Francia y Rusia"], correcta: "a" },
  { pregunta: "¿Quién fue el primer presidente negro de Sudáfrica?", opciones: ["Desmond Tutu","Nelson Mandela","Thabo Mbeki","Jacob Zuma"], correcta: "b" },
  { pregunta: "¿Quién inventó la imprenta de tipos móviles en Europa?", opciones: ["Leonardo da Vinci","Galileo Galilei","Johannes Gutenberg","Martín Lutero"], correcta: "c" },
  { pregunta: "¿Cuál es el planeta más grande del sistema solar?", opciones: ["Saturno","Neptuno","Urano","Júpiter"], correcta: "d" },
  { pregunta: "¿Cuál es el planeta más cercano al Sol?", opciones: ["Venus","Marte","Tierra","Mercurio"], correcta: "d" },
  { pregunta: "¿Cuál es el planeta más caliente del sistema solar?", opciones: ["Venus","Mercurio","Marte","Júpiter"], correcta: "a" },
  { pregunta: "¿Desde qué año Plutón dejó de considerarse planeta?", opciones: ["1999","2010","2015","2006"], correcta: "d" },
  { pregunta: "¿Cuánto tarda la luz del Sol en llegar a la Tierra, aproximadamente?", opciones: ["8 segundos","8 horas","1 día","8 minutos"], correcta: "d" },
  { pregunta: "¿Cuál es la estrella más cercana al Sol?", opciones: ["Sirio","Betelgeuse","Próxima Centauri","Vega"], correcta: "c" },
  { pregunta: "¿Cuál es la velocidad de la luz, aproximadamente?", opciones: ["300.000 km/s","30.000 km/s","3.000.000 km/s","300.000 km/h"], correcta: "a" },
  { pregunta: "¿Cuántos huesos tiene el cuerpo humano adulto?", opciones: ["186","226","206","256"], correcta: "c" },
  { pregunta: "¿Cuál es el hueso más largo del cuerpo humano?", opciones: ["Tibia","Húmero","Fémur","Columna vertebral"], correcta: "c" },
  { pregunta: "¿Cuál es el hueso más pequeño del cuerpo humano?", opciones: ["Yunque","Martillo","Falange","Estribo"], correcta: "d" },
  { pregunta: "¿Qué órgano produce la insulina?", opciones: ["Hígado","Riñón","Estómago","Páncreas"], correcta: "d" },
  { pregunta: "¿Cuántos cromosomas tiene una célula humana normal?", opciones: ["23","46","48","44"], correcta: "b" },
  { pregunta: "¿Cuántos dientes tiene un adulto con la dentadura completa?", opciones: ["32","28","30","36"], correcta: "a" },
  { pregunta: "¿Qué grupo sanguíneo es el donante universal?", opciones: ["O positivo","AB positivo","A negativo","O negativo"], correcta: "d" },
  { pregunta: "¿Qué vitamina produce el cuerpo con la luz del sol?", opciones: ["Vitamina C","Vitamina A","Vitamina B12","Vitamina D"], correcta: "d" },
  { pregunta: "¿Cuál es el elemento químico de símbolo Fe?", opciones: ["Hierro","Flúor","Fósforo","Francio"], correcta: "a" },
  { pregunta: "¿Cuál es el elemento químico de símbolo Au?", opciones: ["Oro","Plata","Aluminio","Argón"], correcta: "a" },
  { pregunta: "¿Qué metal es líquido a temperatura ambiente?", opciones: ["Mercurio","Plomo","Estaño","Litio"], correcta: "a" },
  { pregunta: "¿Cuál es el gas más abundante en la atmósfera terrestre?", opciones: ["Oxígeno","Dióxido de carbono","Nitrógeno","Argón"], correcta: "c" },
  { pregunta: "¿Cuál es el elemento más abundante del universo?", opciones: ["Helio","Oxígeno","Hidrógeno","Carbono"], correcta: "c" },
  { pregunta: "¿Qué gas absorben las plantas para hacer la fotosíntesis?", opciones: ["Oxígeno","Dióxido de carbono","Nitrógeno","Hidrógeno"], correcta: "b" },
  { pregunta: "¿Quién propuso la teoría de la relatividad?", opciones: ["Isaac Newton","Galileo Galilei","Stephen Hawking","Albert Einstein"], correcta: "d" },
  { pregunta: "¿Quién formuló la ley de la gravitación universal?", opciones: ["Isaac Newton","Albert Einstein","Johannes Kepler","Nicolás Copérnico"], correcta: "a" },
  { pregunta: "¿Quién propuso la teoría de la evolución por selección natural?", opciones: ["Gregor Mendel","Louis Pasteur","Jean-Baptiste Lamarck","Charles Darwin"], correcta: "d" },
  { pregunta: "¿Quién fue la primera persona en ganar dos premios Nobel?", opciones: ["Marie Curie","Albert Einstein","Linus Pauling","Niels Bohr"], correcta: "a" },
  { pregunta: "¿Quién descubrió la penicilina?", opciones: ["Louis Pasteur","Robert Koch","Edward Jenner","Alexander Fleming"], correcta: "d" },
  { pregunta: "¿Quién creó la tabla periódica de los elementos?", opciones: ["Antoine Lavoisier","Dmitri Mendeléyev","John Dalton","Marie Curie"], correcta: "b" },
  { pregunta: "¿Cuál es el animal más rápido del mundo?", opciones: ["Guepardo","Halcón peregrino","Pez vela","Águila real"], correcta: "b" },
  { pregunta: "¿Cuál es el animal terrestre más rápido del mundo?", opciones: ["Guepardo","León","Antílope","Liebre"], correcta: "a" },
  { pregunta: "¿Cuál es el animal más grande que existió jamás?", opciones: ["Tiburón ballena","Ballena azul","Elefante africano","Tiranosaurio"], correcta: "b" },
  { pregunta: "¿Cuántos corazones tiene un pulpo?", opciones: ["1","3","2","4"], correcta: "b" },
  { pregunta: "¿Cuál es el único mamífero capaz de volar?", opciones: ["Ardilla voladora","Lémur volador","Murciélago","Colibrí"], correcta: "c" },
  { pregunta: "¿Qué animal puede pasar toda su vida sin beber agua?", opciones: ["Rata canguro","Camello","Tortuga del desierto","Koala"], correcta: "a" },
  { pregunta: "¿Qué animal tiene la mordida más fuerte que se haya medido?", opciones: ["Tiburón blanco","Cocodrilo de agua salada","León","Hipopótamo"], correcta: "b" },
  { pregunta: "¿Qué animal tiene la lengua más larga en relación a su cuerpo?", opciones: ["Jirafa","Camaleón","Oso hormiguero","Rana"], correcta: "b" },
  { pregunta: "¿Qué ave puede girar la cabeza 270 grados?", opciones: ["Halcón","Loro","Búho","Cuervo"], correcta: "c" },
  { pregunta: "¿Cuál es el único felino que no puede retraer del todo las garras?", opciones: ["Tigre","Guepardo","Leopardo","Jaguar"], correcta: "b" },
  { pregunta: "¿Cuál es el felino más grande?", opciones: ["León","Jaguar","Tigre","Puma"], correcta: "c" },
  { pregunta: "¿Cuál es el animal más venenoso del mundo?", opciones: ["Medusa de caja","Mamba negra","Escorpión","Araña de rincón"], correcta: "a" },
  { pregunta: "¿Qué insecto puede sobrevivir varios días sin cabeza?", opciones: ["Hormiga","Mosca","Abeja","Cucaracha"], correcta: "d" },
  { pregunta: "¿Qué animal tiene el corazón más grande en proporción a su cuerpo?", opciones: ["Ballena","Colibrí","Elefante","Ratón"], correcta: "b" },
  { pregunta: "¿Qué ave es capaz de volar hacia atrás?", opciones: ["Águila","Colibrí","Golondrina","Búho"], correcta: "b" },
  { pregunta: "¿Qué animal puede regenerar sus brazos?", opciones: ["Tiburón","Delfín","Estrella de mar","Tortuga"], correcta: "c" },
  { pregunta: "¿Qué lagarto puede correr sobre el agua?", opciones: ["Iguana","Camaleón","Basilisco","Dragón de Komodo"], correcta: "c" },
  { pregunta: "¿Qué animal aparece en el escudo de Australia junto al emú?", opciones: ["Koala","Ornitorrinco","Canguro","Cocodrilo"], correcta: "c" },
  { pregunta: "¿Quién pintó la Mona Lisa?", opciones: ["Miguel Ángel","Leonardo da Vinci","Rafael","Botticelli"], correcta: "b" },
  { pregunta: "¿Quién pintó el \"Guernica\"?", opciones: ["Salvador Dalí","Joan Miró","Pablo Picasso","Francisco de Goya"], correcta: "c" },
  { pregunta: "¿Quién pintó \"La noche estrellada\"?", opciones: ["Claude Monet","Paul Cézanne","Vincent van Gogh","Edvard Munch"], correcta: "c" },
  { pregunta: "¿Quién pintó \"El grito\"?", opciones: ["Edvard Munch","Vincent van Gogh","Gustav Klimt","Salvador Dalí"], correcta: "a" },
  { pregunta: "¿Quién pintó el techo de la Capilla Sixtina?", opciones: ["Leonardo da Vinci","Miguel Ángel","Rafael","Caravaggio"], correcta: "b" },
  { pregunta: "¿Qué pintor es famoso por sus relojes blandos?", opciones: ["René Magritte","Pablo Picasso","Joan Miró","Salvador Dalí"], correcta: "d" },
  { pregunta: "¿Quién escribió \"Don Quijote de la Mancha\"?", opciones: ["Lope de Vega","Miguel de Cervantes","Francisco de Quevedo","Garcilaso de la Vega"], correcta: "b" },
  { pregunta: "¿Quién escribió \"El principito\"?", opciones: ["Julio Verne","Victor Hugo","Antoine de Saint-Exupéry","Albert Camus"], correcta: "c" },
  { pregunta: "¿Quién escribió \"Romeo y Julieta\"?", opciones: ["Charles Dickens","Oscar Wilde","William Shakespeare","Jane Austen"], correcta: "c" },
  { pregunta: "¿Quién escribió \"1984\"?", opciones: ["George Orwell","Aldous Huxley","Ray Bradbury","Franz Kafka"], correcta: "a" },
  { pregunta: "¿Quién escribió \"La metamorfosis\"?", opciones: ["Fiódor Dostoievski","Hermann Hesse","Franz Kafka","Thomas Mann"], correcta: "c" },
  { pregunta: "¿Quién escribió \"El señor de los anillos\"?", opciones: ["C. S. Lewis","George R. R. Martin","J. R. R. Tolkien","J. K. Rowling"], correcta: "c" },
  { pregunta: "¿Quién escribió \"La Odisea\"?", opciones: ["Sófocles","Homero","Virgilio","Platón"], correcta: "b" },
  { pregunta: "¿Quién dirigió \"Titanic\" y \"Avatar\"?", opciones: ["Steven Spielberg","James Cameron","Ridley Scott","Christopher Nolan"], correcta: "b" },
  { pregunta: "¿Quién dirigió \"Jurassic Park\" y \"E.T.\"?", opciones: ["George Lucas","Steven Spielberg","James Cameron","Robert Zemeckis"], correcta: "b" },
  { pregunta: "¿Quién dirigió \"Pulp Fiction\"?", opciones: ["Martin Scorsese","David Fincher","Quentin Tarantino","Guy Ritchie"], correcta: "c" },
  { pregunta: "¿Quién dirigió \"El Padrino\"?", opciones: ["Francis Ford Coppola","Martin Scorsese","Brian De Palma","Sergio Leone"], correcta: "a" },
  { pregunta: "¿De qué país es \"Parásitos\", la primera película no hablada en inglés en ganar el Oscar a mejor película?", opciones: ["Japón","Corea del Sur","China","Tailandia"], correcta: "b" },
  { pregunta: "¿Qué actor interpreta a Iron Man en las películas de Marvel?", opciones: ["Chris Evans","Chris Hemsworth","Robert Downey Jr.","Mark Ruffalo"], correcta: "c" },
  { pregunta: "¿Cómo se llama el protagonista de \"Breaking Bad\"?", opciones: ["Jesse Pinkman","Saul Goodman","Walter White","Hank Schrader"], correcta: "c" },
  { pregunta: "¿De qué país es \"El juego del calamar\"?", opciones: ["Japón","China","Corea del Sur","Corea del Norte"], correcta: "c" },
  { pregunta: "¿En qué ciudad viven Los Simpson?", opciones: ["Shelbyville","Springfield","Quahog","South Park"], correcta: "b" },
  { pregunta: "¿Quién creó a Los Simpson?", opciones: ["Seth MacFarlane","Trey Parker","Matt Groening","Mike Judge"], correcta: "c" },
  { pregunta: "¿En qué casa de Hogwarts está Harry Potter?", opciones: ["Slytherin","Ravenclaw","Gryffindor","Hufflepuff"], correcta: "c" },
  { pregunta: "¿Quién es el padre de Luke Skywalker?", opciones: ["Obi-Wan Kenobi","El Emperador","Darth Vader","Han Solo"], correcta: "c" },
  { pregunta: "¿Cómo se llama el hobbit que lleva el anillo en \"El señor de los anillos\"?", opciones: ["Bilbo","Sam","Frodo","Pippin"], correcta: "c" },
  { pregunta: "¿En qué ciudad vive Batman?", opciones: ["Metrópolis","Gotham","Ciudad Central","Star City"], correcta: "b" },
  { pregunta: "¿De qué planeta viene Superman?", opciones: ["Marte","Krypton","Vulcano","Tatooine"], correcta: "b" },
  { pregunta: "¿Cuál fue el primer largometraje de Pixar?", opciones: ["Bichos","Toy Story","Monsters Inc.","Buscando a Nemo"], correcta: "b" },
  { pregunta: "¿Cómo se llama la cafetería de \"Friends\"?", opciones: ["Central Park","MacLaren's","Central Perk","The Max"], correcta: "c" },
  { pregunta: "¿En qué pueblo transcurre \"Stranger Things\"?", opciones: ["Hawkins","Derry","Castle Rock","Riverdale"], correcta: "a" },
  { pregunta: "¿De qué país es \"La casa de papel\"?", opciones: ["México","Argentina","Colombia","España"], correcta: "d" },
  { pregunta: "¿Qué máscara usan los ladrones de \"La casa de papel\"?", opciones: ["La de Salvador Dalí","La de Guy Fawkes","La de Pablo Picasso","La de Frida Kahlo"], correcta: "a" },
  { pregunta: "¿Qué banda grabó \"Bohemian Rhapsody\"?", opciones: ["The Beatles","Led Zeppelin","Queen","Pink Floyd"], correcta: "c" },
  { pregunta: "¿De qué ciudad eran los Beatles?", opciones: ["Liverpool","Londres","Manchester","Birmingham"], correcta: "a" },
  { pregunta: "¿Quién grabó el disco \"Thriller\", el más vendido de la historia?", opciones: ["Prince","Madonna","Elvis Presley","Michael Jackson"], correcta: "d" },
  { pregunta: "¿Quién fue el cantante de Nirvana?", opciones: ["Eddie Vedder","Chris Cornell","Kurt Cobain","Dave Grohl"], correcta: "c" },
  { pregunta: "¿De qué país es la banda AC/DC?", opciones: ["Estados Unidos","Reino Unido","Australia","Canadá"], correcta: "c" },
  { pregunta: "¿De qué país es la banda ABBA?", opciones: ["Noruega","Dinamarca","Alemania","Suecia"], correcta: "d" },
  { pregunta: "¿Qué cantante puertorriqueño lanzó \"Despacito\" en 2017, con Daddy Yankee de invitado?", opciones: ["Ricky Martin","Maluma","Ozuna","Luis Fonsi"], correcta: "d" },
  { pregunta: "¿Qué compositor siguió componiendo después de quedarse sordo?", opciones: ["Wolfgang Amadeus Mozart","Johann Sebastian Bach","Ludwig van Beethoven","Franz Schubert"], correcta: "c" },
  { pregunta: "¿Quién compuso \"Las cuatro estaciones\"?", opciones: ["Johann Sebastian Bach","Antonio Vivaldi","Wolfgang Amadeus Mozart","Frédéric Chopin"], correcta: "b" },
  { pregunta: "¿Cuántas teclas tiene un piano estándar?", opciones: ["76","96","88","100"], correcta: "c" },
  { pregunta: "¿Qué instrumento tocaba Astor Piazzolla?", opciones: ["Acordeón","Guitarra","Piano","Bandoneón"], correcta: "d" },
  { pregunta: "¿Cada cuántos años se hacen los Juegos Olímpicos de verano?", opciones: ["2","3","5","4"], correcta: "d" },
  { pregunta: "¿Cuántos jugadores tiene un equipo de básquet en la cancha?", opciones: ["6","7","5","4"], correcta: "c" },
  { pregunta: "¿Cuántos jugadores tiene un equipo de vóley en la cancha?", opciones: ["5","6","7","8"], correcta: "b" },
  { pregunta: "¿Cuántos jugadores tiene un equipo de rugby en la cancha?", opciones: ["13","11","17","15"], correcta: "d" },
  { pregunta: "¿Dónde se jugó el Mundial 2022?", opciones: ["Qatar","Rusia","Emiratos Árabes","Arabia Saudita"], correcta: "a" },
  { pregunta: "¿Quién ganó el Mundial 2022?", opciones: ["Francia","Brasil","Argentina","Croacia"], correcta: "c" },
  { pregunta: "¿Quién ganó el Mundial 2014?", opciones: ["Argentina","Alemania","Brasil","Países Bajos"], correcta: "b" },
  { pregunta: "¿Quién ganó el Mundial 2010?", opciones: ["Países Bajos","España","Alemania","Uruguay"], correcta: "b" },
  { pregunta: "¿Qué país tiene más Mundiales de fútbol ganados?", opciones: ["Alemania","Italia","Argentina","Brasil"], correcta: "d" },
  { pregunta: "¿Qué torneo de tenis se juega sobre polvo de ladrillo?", opciones: ["Wimbledon","US Open","Abierto de Australia","Roland Garros"], correcta: "d" },
  { pregunta: "¿Qué torneo de tenis se juega sobre césped?", opciones: ["Roland Garros","US Open","Abierto de Australia","Wimbledon"], correcta: "d" },
  { pregunta: "¿En qué equipo de la NBA se hizo famoso Michael Jordan?", opciones: ["Los Angeles Lakers","Chicago Bulls","Boston Celtics","Miami Heat"], correcta: "b" },
  { pregunta: "¿De qué país es Usain Bolt?", opciones: ["Estados Unidos","Trinidad y Tobago","Jamaica","Bahamas"], correcta: "c" },
  { pregunta: "¿En qué club italiano jugó Diego Maradona?", opciones: ["Juventus","Napoli","Milan","Inter"], correcta: "b" },
  { pregunta: "¿En qué club brasileño se hizo famoso Pelé?", opciones: ["Flamengo","Corinthians","Palmeiras","Santos"], correcta: "d" },
  { pregunta: "¿De qué país es Cristiano Ronaldo?", opciones: ["Portugal","España","Brasil","Argentina"], correcta: "a" },
  { pregunta: "¿Qué piloto brasileño de Fórmula 1 murió en Imola en 1994?", opciones: ["Nelson Piquet","Emerson Fittipaldi","Rubens Barrichello","Ayrton Senna"], correcta: "d" },
  { pregunta: "¿De qué color es el maillot del líder del Tour de Francia?", opciones: ["Amarillo","Verde","Rojo","Blanco"], correcta: "a" },
  { pregunta: "¿Cómo se llama el estadio de Boca Juniors?", opciones: ["El Monumental","El Cilindro","La Fortaleza","La Bombonera"], correcta: "d" },
  { pregunta: "¿En qué ciudad está el estadio Maracaná?", opciones: ["Río de Janeiro","São Paulo","Brasilia","Belo Horizonte"], correcta: "a" },
  { pregunta: "¿De qué país es la paella?", opciones: ["Italia","Portugal","México","España"], correcta: "d" },
  { pregunta: "¿En qué ciudad nació la pizza?", opciones: ["Roma","Nápoles","Milán","Florencia"], correcta: "b" },
  { pregunta: "¿De qué país es el ceviche?", opciones: ["México","Chile","Perú","Ecuador"], correcta: "c" },
  { pregunta: "¿De qué país es la feijoada?", opciones: ["Brasil","Portugal","Angola","Cuba"], correcta: "a" },
  { pregunta: "¿De qué fruta se hace el guacamole?", opciones: ["Tomate","Pepino","Mango","Palta"], correcta: "d" },
  { pregunta: "¿De qué planta se obtiene el chocolate?", opciones: ["Café","Vainilla","Cacao","Algarrobo"], correcta: "c" },
  { pregunta: "¿De qué planta se hace el tequila?", opciones: ["Caña de azúcar","Agave","Maíz","Cactus"], correcta: "b" },
  { pregunta: "¿De qué legumbre se hace el hummus?", opciones: ["Garbanzo","Lenteja","Poroto","Arveja"], correcta: "a" },
  { pregunta: "¿De qué región de Francia es el champán auténtico?", opciones: ["Borgoña","Champaña","Burdeos","Provenza"], correcta: "b" },
  { pregunta: "¿De qué ciudad toma su nombre la milanesa?", opciones: ["Madrid","Marsella","Múnich","Milán"], correcta: "d" },
  { pregunta: "¿Quiénes fundaron Microsoft?", opciones: ["Bill Gates y Paul Allen","Steve Jobs y Steve Wozniak","Larry Page y Sergey Brin","Jeff Bezos y Andy Jassy"], correcta: "a" },
  { pregunta: "¿Qué empresa es dueña de Android?", opciones: ["Apple","Samsung","Google","Microsoft"], correcta: "c" },
  { pregunta: "¿Qué empresa es dueña de WhatsApp e Instagram?", opciones: ["Google","Meta","Microsoft","X"], correcta: "b" },
  { pregunta: "¿Qué empresa es dueña de YouTube?", opciones: ["Google","Meta","Amazon","Microsoft"], correcta: "a" },
  { pregunta: "¿Qué significa \"www\"?", opciones: ["World Web Wide","World Wide Web","Web World Wide","Wide World Web"], correcta: "b" },
  { pregunta: "¿Cuál de estos es un lenguaje de programación?", opciones: ["HTML","HTTP","URL","Python"], correcta: "d" },
  { pregunta: "¿En qué año salió el primer iPhone?", opciones: ["2007","2005","2009","2010"], correcta: "a" },
  { pregunta: "¿Cuántos bits tiene un byte?", opciones: ["4","16","8","10"], correcta: "c" },
  { pregunta: "¿Qué empresa fabrica la PlayStation?", opciones: ["Nintendo","Microsoft","Sony","Sega"], correcta: "c" },
  { pregunta: "¿Qué empresa fabrica la Xbox?", opciones: ["Sony","Microsoft","Nintendo","Sega"], correcta: "b" },
  { pregunta: "¿Quién creó el sistema operativo Linux?", opciones: ["Linus Torvalds","Bill Gates","Steve Jobs","Richard Stallman"], correcta: "a" },
  { pregunta: "¿Qué empresa creó ChatGPT?", opciones: ["Google","OpenAI","Meta","Microsoft"], correcta: "b" },
  { pregunta: "¿Con qué nombre se conoce al creador anónimo de Bitcoin?", opciones: ["Vitalik Buterin","Elon Musk","Julian Assange","Satoshi Nakamoto"], correcta: "d" },
  { pregunta: "¿Cómo empezó Netflix su negocio?", opciones: ["Como canal de cable","Como cine","Alquilando DVD por correo","Vendiendo televisores"], correcta: "c" },
  { pregunta: "¿Qué red social compró Elon Musk en 2022?", opciones: ["Instagram","TikTok","Snapchat","Twitter"], correcta: "d" },
  { pregunta: "¿Quién fundó Amazon?", opciones: ["Jeff Bezos","Elon Musk","Bill Gates","Mark Zuckerberg"], correcta: "a" },
  { pregunta: "¿En qué año nació Wikipedia?", opciones: ["1998","2001","2004","2007"], correcta: "b" },
  { pregunta: "¿Qué tecnología inalámbrica conecta dispositivos a corta distancia, como auriculares?", opciones: ["Bluetooth","Wi-Fi","5G","NFC"], correcta: "a" },
];
